### PR TITLE
feat: request for new repository

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## Description

This PR represents a request for a new repository named `identity-trust`, the purpose of which will be 
to host specification documents regarding topics revolving around identity and trust (a.k.a. "SSI")

\cc @jimmarino @wolf4ood @matgnt @dr-markus @borisrizov-zf

I hope the configuration regarding `gh-pages` is correct, especially the part about the `gh_pages_build_type`, I merely copied it over from another repo. 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by netomi** [comment]
LGTM

**Comment by netomi** [comment]
Is there already a ticket in the sig-infra repo or can someone else approve that?

**Comment by netomi** [comment]
https://github.com/eclipse-tractusx/sig-infra/issues

but I dont know how its now done in the tractus-x project. There were talks about a document to highlight how new resources should be provisioned by whom. Maybe in this case just ask for approval from a project lead?

**Comment by paullatzelsperger** [comment]
> https://github.com/eclipse-tractusx/sig-infra/issues
> 
> but I dont know how its now done in the tractus-x project. There were talks about a document to highlight how new resources should be provisioned by whom. Maybe in this case just ask for approval from a project lead?

@Siegfriedk is it enough to ask for your +1 here or is something else required?

**Comment by Siegfriedk** [comment]
Yes the normal documented workflow is creating a ticket in sig-infra as we discovered that most people are not able to properly create a PR lke this.

A highlight from a project lead shoould be enough without a sig-infra ticket

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created.

**Pull request merged**
