### PR TITLE
chore: add esc-backbone repo

### PR DESCRIPTION
**Pull request by almadigabor**
## Description

Based on this issue https://github.com/eclipse-tractusx/sig-infra/issues/393. Creating new esc-backbone repo so the team can make their initial contribution to the project.

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by almadigabor** [comment]
Hey @Siegfriedk please take a look and confirm.

**Review by fredg02 — APPROVED** [review]

**Comment by almadigabor** [comment]
Hey @fredg02, @netomi! Can you please merge this PR?

**Comment by eclipsewebmaster** [comment]
Change has been applied.

**Comment by fredg02** [comment]
Change has been applied.

**Pull request merged**
