### PR TITLE
chore: update settings for portal repos

### PR DESCRIPTION
**Pull request by evegufy**
## Description

update repository settings for portal-repository:
- change default branch (issue: https://github.com/eclipse-tractusx/portal-cd/issues/66)
- add branch protections rule
- add 'delete branch on merge' setting
- add repo description

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by netomi** [comment]
change LTGM, when you change the default branch to main, you can just remove the setting completely, as it already defined in the default, but thats just a minor nitpick.

Could a second committer / project-lead approve these changes?

**Comment by evegufy** [comment]
> change LTGM, when you change the default branch to main, you can just remove the setting completely, as it already defined in the default, but thats just a minor nitpick.
> 
> Could a second committer / project-lead approve these changes?

@netomi Thank you, I removed the setting for the default branch.

@Siegfriedk Could you please give your approval as project lead?

**Comment by evegufy** [comment]
> > change LTGM, when you change the default branch to main, you can just remove the setting completely, as it already defined in the default, but thats just a minor nitpick.
> > Could a second committer / project-lead approve these changes?
> 
> @netomi Thank you, I removed the setting for the default branch.
> 
> @Siegfriedk Could you please give your approval as project lead?

@SebastianBezold Could you please give your approval? Sigi is on leave I heard.

**Comment by SebastianBezold** [comment]
Hi,

from my point of view the description and branch protection rules are fine, but I'm not sure, if a PL (@giterrific, @danielmiehle, @Siegfriedk) approval is needed.

**Comment by netomi** [comment]
Considering the type of changes, another approval from a fellow committer are enough imho. I will merge at as is.

**Pull request merged**
