### PR TITLE
chore: add new repository

### PR DESCRIPTION
**Pull request by carslen**
add new repository `knowledge-agents-aas-bridge` to eclipse-tractusx GH org as requested in eclipse-tractusx/sig-infra#240

### CODE REVIEW

**Comment by netomi** [comment]
LGTM, just to clarify is the new process that requests are first created in sig-infra and once approved a PR is created here by a system engineer? Is there a list of people who will create PRs so that we can streamline that, e.g. create a new team that we can use for fast approval?

**Comment by carslen** [comment]
We're working on it to get a documeted process here, but it's not yet finished. Unfortunately, there is no public available list for current sig-infra/System-Team members.

**Comment by netomi** [comment]
ok I will approve for now. Keep me updated on the document. I would be happy to implement a custom approval process for each project to fit their needs to make this tool as useful as posssible.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created. I might take 1-2 hours for the permissions to be set correctly.

**Pull request merged**
