### PR TITLE
chore: request new template repo

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## Description

Requesting a new template repository, which will serve as starting point for everyone who wants to create their
own variant (="distribution") of EDC.
## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by Siegfriedk** [comment]
@paullatzelsperger why the tractus-x prefix? tractus-x is already part of the org 'scope'

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger why the tractus-x prefix? tractus-x is already part of the org 'scope'

the "origin" repo is called `tractux-edc`, so it seemed reasonable to call this `tractusx-edc-template` to keep consistency.

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger i see. Makes sense, it would make sense to rename edc too, but probably too late for that.

it probably is, and that could create even more confusion than we already have with "Tx-EDC vs (upstream) EDC"

**Comment by netomi** [comment]
so is the change accepted?

**Comment by paullatzelsperger** [comment]
@Siegfriedk @netomi is there anything left to do or can we merge this?

**Comment by Siegfriedk** [comment]
Nothing to do from my side, i gave thumbs up already

**Comment by netomi** [comment]
ok so the thumbs up does not trigger a notification.

**Review by netomi — APPROVED** [review]

**Pull request merged**
