### PR TITLE
chore: add new bpdm-certificate-management repo

### PR DESCRIPTION
**Pull request by SebastianBezold**
## Description

Adding a new uninitialized repo `bpdm-certificate-management`, liked requested in eclipse-tractusx/sig-infra#310 

FYI @SujitMBRDI , @nicoprow. Please initialize the repository with at least the legal docs, as soon as it is created

### CODE REVIEW

**Comment by SebastianBezold** [comment]
Hi @netomi, I'm unsure, why the validate step failed. Seems like the jsonnet bundler could not be pulled, although the referenced tag does exist. Did you experience such an issue before?

**Comment by netomi** [comment]
yeah, that seems to be a temporary issue with GitHub as also seen in other PRs today.
Well we have plans to remove the dependency on this component but it will still need some time.

The change LGTM, so will merge as is.

**Comment by netomi** [comment]
actually the problem seems to be with proxy.golang.org not with github itself.

**Comment by netomi** [comment]
repo has been created.

**Pull request merged**
