### PR TITLE
fix(puris): use syntax for reusable workflow for CodeQl

### PR DESCRIPTION
**Pull request by tom-rm-meyer-ISST**
## Description

Recent pr #81 didn't consider CodeQl workflow as a reused one (wrong).

This pr handles CodeQl as reusable workflow (correct, following the results in this [pr](https://github.com/eclipse-tractusx/puris/pull/450)).

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
I am not sure if all these status checks use the correct convention. I tried to collect the rules how the status checks need to be referenced here: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/status-check/

I can also double check via the UI what names are required if needed.

**Comment by tom-rm-meyer-ISST** [comment]
> I am not sure if all these status checks use the correct convention. I tried to collect the rules how the status checks need to be referenced here: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/status-check/
> 
> I can also double check via the UI what names are required if needed.

Hey @netomi,

I only got an issue with Code Ql. I'll raise a ticket for that.

**Comment by tom-rm-meyer-ISST** [comment]
> I am not sure if all these status checks use the correct convention. I tried to collect the rules how the status checks need to be referenced here: https://otterdog.readthedocs.io/en/latest/reference/organization/repository/status-check/
> 
> I can also double check via the UI what names are required if needed.

Hey @netomi, could you please check the required names including codeql? I currently see that also my docker jobs fail and it seems that I didn't get the documentation right :(

Can you also tell me how to read out the names from the dashboard? Then I brief my project regarding the correct usage :)

**Comment by netomi** [comment]
so the rule seems to be that you take the name of a job as status check if it exists, otherwise its id

for example in the case of CodeQL, you have that in your workflow:

```
jobs:
  analyze:
    name: Analyze
```

the status check would be Analyze, which is ofc very generic, so giving it a more meaningful name is useful.

For docker, its a bit confusing, there are 2 workflows for backend and frontend, but both have a job with id docker and no name, so in the UI I selected just docker as status check and that seems to work, not sure what happens in the background in such a case, but I would give them distinctive names.

**Comment by tom-rm-meyer-ISST** [comment]
> so the rule seems to be that you take the name of a job as status check if it exists, otherwise its id
> 
> for example in the case of CodeQL, you have that in your workflow:
> 
> ```
> jobs:
>   analyze:
>     name: Analyze
> ```
> 
> the status check would be Analyze, which is ofc very generic, so giving it a more meaningful name is useful.
> 
> For docker, its a bit confusing, there are 2 workflows for backend and frontend, but both have a job with id docker and no name, so in the UI I selected just docker as status check and that seems to work, not sure what happens in the background in such a case, but I would give them distinctive names.

I noticed the same behavior and try to fix it with this pr: https://github.com/eclipse-tractusx/puris/pull/450

- renamed job ids for docker (`docker-backend` and `docker-frontend`)
- Made Code Ql and KICS Name less generic
- updated the helm workflow as intended

**Pull request merged**
